export const Categories = {
  Electricity: {
    'Distribution Board': [
      'Main CircuitBreaker Installation',
      'Mini Circuit Breaker Installation',
      'Others',
    ],
    Lighting: [
      'Chanddellier Installation',
      'Light Bulb Replacement',
      'Light Fixture Installation',
      'Light Switch Repair/ Replacement',
      'Switches & Power Outlets',
      'Conventional Electrical Switch repair or replacement',
      'New Power outlet installation',
      'Short Circuit',
      'Single power outlet repair or replacement',
      'Twin power outlet repair or replacement',
      'window Exhaust Fan Installation',
      'Others',
    ],
    Others: ['Others'],
  },
  'Air Conditioner': {
    'Air Conditioner': [
      'No Cooling',
      'Insufficient Cooling',
      'Uneven Cooling',
      'Noisy Operation',
      'Frequent Cycling',
      'Leaking Water',
      'Frozen Evaporator Coil',
      'Dirty or Clogged Air Filters',
      'Refrigerant Leak',
      'Thermostat Issues',
      'Electrical Problems',
      'Fan Problems',
      'Others',
    ],
    Others: ['Others'],
  },
  Heater: {
    Heater: [
      'No Heat',
      'Insufficient Heat',
      'Uneven Heating',
      'Noisy Operation',
      'Short Cycling',
      'Pilot Light Problems',
      'Carbon Monoxide Leaks',
      'Dirty or Clogged Air Filters',
      'Thermostat Issues',
      'Ignition or Igniter Problems',
      'Electrical Issues',
      'Pilot Control Valve Problems',
      'Others',
    ],
    Others: ['Others'],
  },
  Landscaping: {
    Landscaping: [
      'Lawn Care and Maintenance',
      'Planting and Garden Design',
      'Irrigation System Installation and Repair',
      'Tree and Shrub Care',
      'Hardscape Installation',
      'Landscape Lighting',
      'Mulching and Weed Control',
      'Seasonal Clean-up',
      'Pest and Disease Management',
      'Water Features and Outdoor Structures',
      'Others',
    ],
    Others: ['Others'],
  },
  PestControl: {
    'General Pest Control ': ['Ants', 'Cockroaches', 'Rodents', 'Bed bugs', 'Others'],
    Others: ['Others'],
  },
  'General Contractor': {
    'TV Mounting': [
      'Request Assessment',
      'Cable Arrangement',
      'TV Dismounting and Remounting',
      'TV Mounting ',
      'Others',
    ],
    Hanging: [
      'Hanging a Small Frame',
      'Hanging a Medium Frame',
      'Hanging a Large Frame',
      'Hanging a Small to Medium Mirror',
      'Hanging a Large Mirror ',
      'Others',
    ],
    'Window Curtains': [
      'Large Window Curtain Installation',
      'Small to Medium Window Curtain Installation',
      'Office Window Blind Installation',
      'Others',
    ],
    WoodWorking: [
      'Custom Furniture Design and Construction',
      'Cabinet Making and Installation',
      'Woodworking for Interior Trim and Molding',
      'Wood Flooring Installation and Refinishing',
      'Custom Woodworking Projects (Shelving, Built-ins, etc.)',
      'Wood Door Construction and Installation',
      'Wood Staircase Design and Construction',
      'Wood Deck and Patio Construction',
      'Wood Fence and Gate Construction',
      'Wood Restoration and Repair Services',
      'Others',
    ],
    'Wall Drill': ['Others'],
    Others: ['Others'],
  },
  Plumbings: {
    Sink: [
      'Sink Accessory Installation',
      'Sink Component Installation',
      'Sink mixer Installation',
      'Sink Repair or Replacement',
      'Valve Replacement',
      'Others',
    ],
    'Shower/Bathtub': [
      'Shower Door Repair',
      'Shower mixer installation',
      'Shower stand installation',
      'Valve replacement',
      'Others',
    ],
    Toilet: [
      'Float Lever Replacement',
      'Toilet Cover Installation or Replacement',
      'Toilet Flush Repair',
      'Toilet Leak Repair',
      'Toilet Removal and Installaton',
      'Valve Replacement',
      'Water Hose Installation or Replacement',
      'Water Hose Mixer Repair or Replacement',
      'Others',
    ],
    'Piping & Water Tanks': [
      'Exposed Leaking Pipes Repair',
      'Float Lever Replacement',
      'Valve Replacement',
      'Water Tank Installation',
      'Water Tank Leak Repair',
      'Water Tank Transportation',
      'Others',
    ],
    Boiler: ['Central water heater replacement', 'Conventional Water Heater Replacement', 'Others'],
    Filters: [
      'Central Filter Repair',
      'Central Filter Replacement',
      'English Design Ceramic Filter Maintenance',
      'English Design Ceramic Filter Replacement',
      'New Filter Installation',
      'Transparent Double Filter Replacement',
      'Transparent Filter Maintenance',
      'Transparent Single Filter Replacement',
      'Others',
    ],
    Pumps: ['Water Pump Installation', 'Water Pump Maintenance'],
    'Clogged Drains': [
      'Air & Water Pressure Machine',
      'Drain Jack Unclogging',
      'Large Manhole',
      'Long Drain Jack Unclogging',
      'Manual Unclogging',
      'Medium Manhole',
      'Small Manhole ',
      'Others',
    ],
    Others: ['Others'],
  },
  Cleaning: {
    'Hourly Cleaning': [
      'Hourly Cleaning With Materials',
      'Hourly Cleaning Without Materials',
      'Others',
    ],
    'Deep Cleaning': {
      Studio: ['Others'],
    },
    'Furniture Cleaning': [
      'King Mattress',
      'Queen Mattress',
      'Single Mattress',
      'Baby Mattress',
      'Pillow',
      'Carpet-Up to 10 sqm',
      'Carpet-Up to 15 sqm',
      'Carpet-Up to 25 sqm',
      'Carpet-Up to 30-sqm',
      'Curtains-4-pieces',
      'Curtains-6 pieces',
      'Sofa ',
      'Others',
    ],
    Others: ['Others'],
  },
  Remodeling: {
    Remodeling: [
      'Kitchen Remodeling',
      'Bathroom Remodeling',
      'Basement Finishing',
      'Room Additions',
      'Flooring Installation',
      'Roofing and Siding',
      'Window and Door Replacement',
      'Deck or Patio Construction',
      'Exterior Renovation',
      'Whole House Renovation',
      'Others',
    ],
    Others: ['Others'],
  },
  Flooring: {
    Flooring: [
      'Hardwood Flooring Installation',
      'Laminate Flooring Installation',
      'Tile Flooring Installation',
      'Carpet Installation',
      'Vinyl Flooring Installation',
      'Engineered Wood Flooring Installation',
      'Concrete Flooring',
      'Subfloor Repair and Preparation',
      'Floor Refinishing',
      'Floor Maintenance and Repair',
      'Others',
    ],
    Others: ['Others'],
  },
  'Windows and doors': {
    WindowsDoors: [
      'Window Installation',
      'Door Installation',
      'Window Replacement',
      'Door Replacement',
      'Custom Window and Door Design',
      'Window and Door Repair',
      'Window and Door Sealing and Insulation',
      'Window and Door Trim and Casing',
      'Window and Door Hardware Upgrades',
      'Skylight Installation and Repair',
      'Others',
    ],
    Others: ['Others'],
  },
  Fencing: {
    Fencing: [
      'Fence Installation',
      'Fence Repair',
      'Fence Replacement',
      'Fence Design and Planning',
      'Gate Installation',
      'Gate Repair and Automation',
      'Fence Staining or Painting',
      'Fence Maintenance',
      'Fence Restoration',
      'Specialty Fencing Services',
      'Others',
    ],
    Others: ['Others'],
  },
  Pool: {
    Pool: [
      'Pool Design and Planning',
      'Pool Excavation',
      'Pool Plumbing and Electrical Installation',
      'Pool Reinforcement and Structure Building',
      'Pool Deck and Patio Construction',
      'Pool Tile and Coping Installation',
      'Pool Equipment Installation (Pumps, Filters, Heaters)',
      'Pool Lighting Installation',
      'Pool Water Features Installation (Waterfalls, Fountains)',
      'Pool Finishing and Interior Surface Application',
      'Others',
    ],
    Others: ['Others'],
  },
  'Auto Body': {
    'Auto Body': ['Paint', 'Body Work', 'Others'],
    Others: ['Others'],
  },

  'Auto Repair': {
    'Auto Repair': ['Transmission Replacement', 'Others'],
    Others: ['Others'],
  },
  'Need Help': {},
};

export const ElectricityCategories = {
  'Distribution Board': ['Main CircuitBreaker Installation', 'Mini Circuit Breaker Installation'],
  Lighting: [
    'Chanddellier Installation',
    'Light Bulb Replacement',
    'Light Fixture Installation',
    'Light Switch Repair/ Replacement',
    'Light Switch Repair/ Replacement',
    'Switches & Power Outlets',
    'Conventional Electrical Switch repair or replacement',
    'New Power outlet installation',
    'Short Circuit',
    'Single power outlet repair or replacement',
    'Twin power outlet repair or replacement',
    'window Exhaust Fan Installation',
  ],
};
